export const AUTH_SERVICE = "AUTH_SERVice"
export const RESERVATION_SERVICE = "RESERVATIOn_SERVice"
export const PAYMENT_SERVICE = "PAYMENT_SERVice"
export const NOTIFICATION_SERVICE = "NOTIFICATION_SERVICE"